#%RAML 1.0
---

title: Residency status for relief at source
version: 2.0
protocols: [ HTTPS ]
baseUri: http://api.service.hmrc.gov.uk

documentation:
  - title: Overview
    content: !include documentation/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing the API
    content: !include documentation/testing-approach.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml

mediaType: [ application/json, application/hal+json ]

/individuals/relief-at-source:
  /residency-status:
    post:
      description: !include documentation/description.md
      displayName: Check if an individual is a Scotland, Wales or rest of the UK resident
      is: [headers.acceptHeader, headers.contentHeader]
      (annotations.scope): "read:ras"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:ras" ] } ]
      (annotations.sandboxData): !include testdata/get-residency-status.md
      body:
        application/json:
            example: !include examples/residency_status_request.ex.json
            type: !include schemas/residency_status.schema.json
      responses:
        200:
          body:
            application/json:
              type: !include schemas/getResidencyStatus.schema.json
              example: |
                {
                  "currentYearResidencyStatus" : "otherUKResident",
                  "nextYearForecastResidencyStatus" : "scotResident"
                }
        400:
          body:
            application/json:
              type: !include schemas/ErrorCodes.schema.json
              description: Bad Request
              example: |
                {
                  "code" : "BAD_REQUEST",
                  "message" : "Bad Request"
                }
        403:
          body:
            application/json:
              description: The pension scheme member's details do not match with HMRC's records.
              type: !include schemas/ErrorCodes.schema.json
              example: |
                {
                  "code": "STATUS_UNAVAILABLE",
                  "message": "Cannot provide a residency status for this pension scheme member."
                }
